import { readFileSync, writeFileSync } from "node:fs"
import { tokenErrors, type Tokens } from "./lib/contrast.ts"
import { readManifest, upsertItem, writeManifest } from "./lib/manifest.ts"
import { themeItem, toCss } from "./lib/theme.ts"

const tokens: Tokens = JSON.parse(readFileSync("tokens/theme.json", "utf8"))
const errors = tokenErrors(tokens)
if (errors.length) {
  console.error(errors.join("\n"))
  process.exit(1)
}
for (const path of ["registry.react.json", "registry.vue.json"]) {
  writeManifest(path, upsertItem(readManifest(path), themeItem(tokens)))
}
writeFileSync("src/theme.css", "/* Generated by scripts/sync-theme.ts from tokens/theme.json — do not edit. */\n" + toCss(tokens))
console.log("saqara-theme synced")
